name: jumma
description: "Jumma application with Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  dartz: ^0.10.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/vectors/
    - assets/images/
    - assets/json/


  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Regular.ttf
        - asset: assets/fonts/dm_sans/DMSans_18pt-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/dm_sans/DMSans_18pt-Light.ttf
          weight: 400